config/routes.rb
Socialfeed::Application.routes.draw do
  require 'sidetiq/web'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :feeds
  resources :entries
  resources :categories
  resources :filters
  resources :notifications
  resources :followings, only: [:index, :create, :destroy]

  devise_scope :user do
    authenticated :user do
      root to: 'entries#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/feed.rb
require 'feedjira'

class Feed < ActiveRecord::Base
  acts_as_tenant :user
  before_validation :set_default_name, if: Proc.new { |feed| feed.name.blank? }
  #
  # schema
  #
  fields do
    name          :string
    url           :string
    description   :text
    etag          :string
    last_modified :datetime
    user_id       :integer
    timestamps
  end
  
  attr_accessible :name, :url, :description, :category_id

  #
  # Validations
  # 
  validates :url, presence: true, feed_url: true
  validates :category_id, presence: true
  validates :name, presence: true
  validates_uniqueness_to_tenant [:name, :url]
  #
  # Relations
  # 
  has_many   :entries, dependent: :destroy
  has_one    :notification, dependent: :destroy
  has_one    :filter, dependent: :destroy
  belongs_to :category
  #
  # Methods
  # 

  def get_latest_entries n
    entries.sort.first(n)
  end

  def update_entries
    feed = Feedjira::Feed.fetch_and_parse(url)
    raise 'Feed format issue' if feed.is_a? Numeric
    notification_entries = []
    unless self.etag == feed.etag && self.last_modified == feed.last_modified
      apply_filter!(feed) if filter._?.active
      user = User.find(user_id)
      if notification._?.active
        notification_entries = search_notification_entries(feed, user)
      end
      self.etag = feed.etag
      self.last_modified = feed.last_modified
      Entry.add_entries(feed.entries.first(50), self.id, user_id)
    end
    notification_entries
  end

  protected
    def set_default_name
      self.name = Feedjira::Feed.fetch_and_parse(url).title
    rescue Exception => e
    end
    
    # filter out entries
    def apply_filter! feed
      keywords = filter.keywords.split(',')
      entries = feed.entries.select do |entry|
        if filter.list_type # whitelisting
          entry_contains_any_keyword?(entry, keywords)
        else # blacklisting
          !entry_contains_any_keyword?(entry, keywords)
        end
      end
      feed.entries = entries
    end

    # run email notifications
    def search_notification_entries feed, user
      keywords = notification.keywords.split(',')
      notification_entries = []
      feed.entries.each do |entry|
        if !Entry.exists?(guid: entry.id) && entry_contains_any_keyword?(entry, keywords)
          notification_entries << entry
        end
      end
      notification_entries
    end

    # check if the entry contains any of the keywords
    def entry_contains_any_keyword? entry, keywords
      keywords.any? do |keyword| 
        entry.title.include?(keyword) || 
        entry.summary.include?(keyword) ||
        entry._?.content._?.include?(keyword)
      end
    end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def index
   @feeds = Feed.all
  end

  def show
    @feed = Feed.find params[:id]
  end

  def new
    @feed = Feed.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @feed = FeedsService.create current_user, params
    respond_to do |format|
      if @feed.errors.empty?
        @entries, @q = EntriesService.current_entries 50
        @entries = EntryDecorator.decorate_collection @entries
        @feeds = Feed.all
        format.js
      else
        format.js{ render 'new', status: :unprocessable_entity }
      end
    end
  end

  def destroy
    feed = FeedsService.destroy params
    respond_to do |format|
      if feed.errors.empty?
        @categories = Category.all
        format.js { render 'categories/refresh_list', status: :ok }
      else
        format.js { render 'destroy_error', status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_entry.html.haml
.entry.panel.panel-default
  #headingOne.panel-heading{:role => "tab"}
    .panel-title
      %a.collapsed{"aria-controls" => "collapse#{entry.id}", "aria-expanded" => "true", "data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapse#{entry.id}"}
        .row
          .col-xs-5
            .name.pull-left
              = truncate entry.name, length: 40
          .col-xs-4
            .published-at
              = time_ago_in_words entry.published_at
          .col-xs-2
            .feed.pull-right
              = link_to entry.feed_name, feed_path(entry.feed)
          .col-xs-1
            .icon.pull-right{class: entry.favorite ? 'favorited' : 'unfavorited'}
              c
          .col-xs-12
  .panel-collapse.collapse{"aria-labelledby" => "headingOne", :role => "tabpanel", id: "collapse#{entry.id}"}
    .panel-body.summary
      = raw entry.summary

app/views/feeds/_feed_form.html.haml
= simple_form_for feed, remote: true do |f|
  .modal-body
    .row
      .col-xs-12
        .panel
          = render 'form_fields', f: f
          .clearfix
    .row
      .col-xs-5.col-xs-offset-7
        .pull-right
          %button.btn{type: "button", data: {dismiss: "modal"}}
            %span.text
              = t('.cancel')
          %button.btn.js-submit{type: "button", data: { disable_with: t('.adding') }}
            %span.text
              = t('.add')

app/views/feeds/_form_fields.html.haml
= f.input :url, required: false, placeholder: t('.paste_url_here'), wrapper_html: {class: 'form-group'}, input_html: {class: 'form-control'}
= f.association :category, as: :select, required: false, selected: Category.undefined, wrapper_html: {class: 'form-group'}, input_html: {class: 'form-control'}
= f.input :name, required: false, placeholder: t('.give_custom_title'), wrapper_html: {class: 'form-group'}, input_html: {class: 'form-control'}
= f.input :description, placeholder: t('.add_description'), wrapper_html: {class: 'form-group'}, input_html: {class: 'form-control', rows: 4}

app/views/feeds/_modal_new_feed_form.html.haml
/ Button trigger modal
= link_to new_feed_path, remote: true, class: "#{'not-active' if @user}" do
  .btn.icon
    g

/ Modal
#add-feed-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content.js-form-container

app/views/feeds/destroy_error.js.erb
$(document).ready(function(){
  alert('Could not delete feed'); //TODO: Apply I18n and use Bootstrap alert
});

app/views/feeds/index.html.haml
.dashboard
	
.feeds
  #accordion.panel-group{"aria-multiselectable" => "true", :role => "tablist"}
    - @entries.each do |entry|
      = render 'entry', entry: entry

app/views/feeds/new.js.erb
$(document).ready(function(){
  var feed = new Feed();
  $form = $("<%= j render 'feed_form', feed: @feed %>");
  feed.refresh_form($form);
});