config/routes.rb
Socialfeed::Application.routes.draw do
  require 'sidetiq/web'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :feeds
  resources :entries
  resources :categories
  resources :filters
  resources :notifications
  resources :followings, only: [:index, :create, :destroy]

  devise_scope :user do
    authenticated :user do
      root to: 'entries#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  acts_as_tenant :user
  #
  # schema
  #
  fields do
    keywords :string
    active   :boolean, default: true
    user_id  :integer
    timestamps
  end

  attr_accessible :keywords, :active, :feed_id

  #
  # Validations
  # 
  validates :user_id, presence: true
  validates :keywords, presence: true

  #
  # Relations
  # 
  belongs_to :feed
  #
  # Methods
  # 

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

  def index
    @feeds = Feed.all
    @user = current_user
    if params[:id]
      @feed = Feed.find params[:id]
      if @feed.notification
        @notification = @feed.notification
      else
        @notification = Notification.new feed_id: @feed.id
      end
    end
    respond_to do |format|
      format.html
      format.js { render 'refresh_form', status: :ok }
    end
  end

  def update
    @notification = NotificationsService.update params
    respond_to do |format|
      if @notification.errors.empty?
        format.js
      else
        format.js{ render 'refresh_form', status: :unprocessable_entity }
      end
    end
  end  

  def destroy
    @notification = NotificationsService.destroy params
    respond_to do |format|
      if @notification.errors.empty?
        @feeds = Feed.all
        @notification = nil
        format.js { render 'refresh_all', status: :ok }
      else
        format.js { render 'refresh_form', status: :unprocessable_entity }
      end
    end
  end

  def create
    @notification = NotificationsService.create params
    respond_to do |format|
      if @notification.errors.empty?
        format.js
      else
        format.js{ render 'refresh_form', status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_feed_selection.html.haml
.row
  = form_tag notifications_path, method: :get, remote: true do |f|
    .col-xs-12
      = select_tag :id, options_from_collection_for_select(feeds, :id, :name, feed._?.id), include_blank: true, class: 'form-control', data: {placeholder: t('placeholders.select_feed')} 

app/views/notifications/_notification_form.html.haml
- if notification
  = simple_form_for notification, remote: true, html: {class: 'top-margin bottom-margin'} do |f|
    .row
      .col-xs-12
        = f.input :keywords, required: false, wrapper_html: {class: 'form-group keywords'}, input_html: {class: 'form-control', rows: 3, data: {role:'tagsinput'}}
      .col-xs-12
        = f.input :active, as: :boolean, input_html: {class: 'checkbox'}, wrapper_html: {class: 'filter-active'}
        = f.input :feed_id, as: :hidden
    .row.top-margin
      .col-xs-2.col-xs-offset-8
        - if notification.persisted?
          = link_to notification_path(notification), method: :delete, remote: true, class: 'btn' do
            = t('.delete')
      .col-xs-2
        %button.btn.js-submit
          = t('.apply')

app/views/notifications/_user_notifications.html.haml
%h3
  = t('.general_notifications')
%p
  = t('.turn_general_user_level_notifications')
= simple_form_for user, url: url_for(action: 'update', controller: 'users/registrations'), method: :put, remote: true do |f|
  .checkbox-group
    .row
      .col-xs-12
        = f.input :notify_new_follower, as: :boolean, wrapper_html: {class: 'form-group'}
    .row
      .col-xs-12
        = f.input :notify_site_updates, as: :boolean, wrapper_html: {class: 'form-group'}
    .row
      .col-xs-12
        = f.input :notify_important_topics, as: :boolean, wrapper_html: {class: 'form-group'}
  .row
    .col-xs-2.col-xs-offset-10
      %button.btn.js-submit
        = t('.apply')

app/views/notifications/create.js.erb
$(document).ready(function(){
  var app = new App();
  $notification_form = $("<%= j render 'notification_form', notification: @notification %>");
  app.refresh_content($('.js-form-container'), $notification_form, function(){
    app.apply_tagsinput();
  });
  alert('notification created successfully');
});

app/views/notifications/index.html.haml
.secondary-view
  .panel
    .row
      .col-xs-8.col-xs-offset-2
        %h2
          = t('.notifications')
        %p
          = t('.choose_keywords_for_each')
        .box
          .js-selection-form
            = render 'feed_selection', feeds: @feeds, feed: @feed
          .js-form-container
            = render 'notification_form', notification: @notification
        .box
          .js-checklist-container
            = render 'user_notifications', user: @user

= content_for :bottom_js do
  = javascript_include_tag "categories/categories"

app/views/notifications/refresh_all.js.erb
$(document).ready(function(){
  var app = new App();
  $notification_form = $("<%= j render 'notification_form', notification: @notification %>");
  app.refresh_content($('.js-form-container'), $notification_form, function(){
    $feed_selection = $("<%= j render 'feed_selection', feeds: @feeds, feed: @feed %>");
    app.refresh_content($('.js-selection-form'), $feed_selection, function(){
      app.apply_select2();
    });
  });
});

app/views/notifications/refresh_form.js.erb
$(document).ready(function(){
  var app = new App();
  $notification_form = $("<%= j render 'notification_form', notification: @notification %>");
  app.refresh_content($('.js-form-container'), $notification_form, function(){
    app.apply_tagsinput();
  });
});

app/views/notifications/refresh_user_notifications_form.js.erb
$(document).ready(function(){
  alert('General notifications successfully updated');
});

app/views/notifications/update.js.erb
$(document).ready(function(){
  var app = new App();
  $notification_form = $("<%= j render 'notification_form', notification: @notification %>");
  app.refresh_content($('.js-form-container'), $notification_form, function(){
    app.apply_tagsinput();
  });
  alert('notification updated successfully');
});