config/routes.rb
Socialfeed::Application.routes.draw do
  require 'sidetiq/web'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :feeds
  resources :entries
  resources :categories
  resources :filters
  resources :notifications
  resources :followings, only: [:index, :create, :destroy]

  devise_scope :user do
    authenticated :user do
      root to: 'entries#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  acts_as_tenant :user
  before_destroy :check_if_destroyable
  before_update :check_if_editable
  #
  # schema
  #
  fields do
    name        :string
    tags        :string
    description :text
    editable    :boolean, default: true
    timestamps
  end

  attr_accessible :name, :tags, :description, :editable, :user_id

  #
  # Validations
  # 
  validates :name, presence: true
  validates_uniqueness_to_tenant :name
  #
  # Scopes
  # 
  scope :undefined, -> { where(editable: false) }

  #
  # Relations
  # 
  has_many   :feeds, dependent: :destroy
  belongs_to :user
  #
  # Methods
  # 
  protected
    def check_if_destroyable
      raise I18n.t('errors.can_not_be_destroyed') unless editable
    end
    def check_if_editable
      raise I18n.t('errors.can_not_be_edited') unless editable
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.order('name desc').all
    @category = Category.new
  end

  def show
    @categories = [Category.find(params[:id])]
    @category = Category.new
    respond_to do |format|
      format.html { render 'index', status: :ok }
    end
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.js { render 'refresh_form', status: :ok }
    end
  end

  def edit
    @category = CategoriesService.edit params
    respond_to do |format|
      if @category.errors.empty?
        format.js { render 'refresh_form', status: :ok }
      else
        @error = @category.errors.full_messages.first
        format.js { render 'error', status: :ok }
      end
    end
  end

  def update
    @category = CategoriesService.update params
    respond_to do |format|
      if @category.errors.empty?
        @categories = Category.all
        @category = Category.new
        format.js { render 'refresh_all', status: :ok }
      else
        format.js { render 'new', status: :ok }
      end
    end
  end  

  def create
    @category = CategoriesService.create params
    respond_to do |format|
      if @category.errors.empty?
        @categories = Category.all
        @category = Category.new
        format.js { render 'refresh_all', status: :ok }
      else
        format.js { render 'new', status: :ok }
      end
    end
  end

  def destroy
    category = CategoriesService.destroy params
    respond_to do |format|
      if category.errors.empty?
        @categories = Category.all
        format.js { render 'refresh_list', status: :ok }
      else
        @error = category.errors.full_messages.first
        format.js { render 'error', status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_title category
    title = ''
    title += I18n.t('categories.index.description') + ": #{category.description}<br>" unless category.description.blank?
    title += I18n.t('categories.index.tags') + ": #{category.tags}" unless category.tags.blank?
    title.chomp
  end
end

app/views/categories/_categories_list.html.haml
- categories.each do |category|
  = render 'categories/category', category: category

app/views/categories/_category.html.haml
.subpanel
  .row
    .col-xs-1
      - if category.feeds.any?
        .icon{data: {toggle: "collapse", target: "#category-feeds#{category.id}"}, aria: {expanded: "false", controls: "collapseExample"}}
          a
    .col-xs-10
      %span.title{data: {toggle: "tooltip", placement: "top"}, title: category_title(category)}
        - if category.editable
          = link_to category.name, edit_category_path(category), remote: true
        - else
          = category.name
    .col-xs-1
      - if category.editable
        = link_to category_path(category), method: :delete, remote: true, data: {confirm: category.feeds.any? ? t('.are_you_sure') : nil} do
          .btn.icon.delete-btn
            e
  .feeds.row.collapse{id: "category-feeds#{category.id}"}
    - category.feeds.each do |feed|
      .col-xs-1
        = link_to feed_path(feed), method: :delete, remote: true do
          .icon.small
            e
      .col-xs-11
        %span{data: {toggle: "tooltip", placement: "right"}, title: feed.url}
          = feed.name

app/views/categories/_category_form.html.haml
%h3
  .row
    - unless action_name == 'edit'
      .col-xs-12
        = t('.new')
    - else
      .col-xs-8
        = t('.edit')
      .col-xs-4
        = link_to t('.new'), new_category_path(), remote: true, class: 'btn'
= simple_form_for @category, remote: true do |f|
  = f.input :name, required: false, placeholder: t('.enter_category_name'), wrapper_html: {class: 'form-group'}, input_html: {class: 'form-control'}
  = f.input :description, placeholder: t('.enter_description'), wrapper_html: {class: 'form-group description'}, input_html: {class: 'form-control', rows: 3}
  = f.input :tags, placeholder: t('.enter_tags'), wrapper_html: {class: 'form-group tags'}, input_html: {class: 'form-control', data: {role: 'tagsinput'}}
  %button.btn.icon
    g

app/views/categories/create.js.erb
$(document).ready(function(){
  $categories_list = $("<%= j render 'entries/entries', entries: @entries %>");
  $categories_container = $('.js-categories-list-container')  ;
  $categories_container.fadeOut("slow", function() {
    $categories_container.html($categories_list);
    $categories_container.fadeIn('slow');
  });
});

app/views/categories/error.js.erb
$(document).ready(function(){
  alert('<%= @error %>');
});

app/views/categories/index.html.haml
.secondary-view
  .panel
    .row
      .col-xs-8.col-xs-offset-2
        %h2
          = t('.categories')
        %p
          = t('.create_a_new_category')
        .box
          .js-category-form-container
            = render 'category_form', category: @category
        .box
          %h3 
            = t('.list')
          .js-categories-list-container
            = render 'categories_list', categories: @categories

= content_for :bottom_js do
  = javascript_include_tag "categories/categories"

app/views/categories/new.js.erb
$(document).ready(function(){
  var category = new Category();
  $category_form = $("<%= j render 'category_form', category: @category %>");
  category.refresh_form($category_form);
});

app/views/categories/refresh_all.js.erb
$(document).ready(function(){
  var category = new Category();
  $category_form = $("<%= j render 'category_form', category: @category %>");
  category.refresh_form($category_form);

  $categories_list = $("<%= j render 'categories/categories_list', categories: @categories %>");
  category.refresh_list($categories_list);
});

app/views/categories/refresh_form.js.erb
$(document).ready(function(){
  var category = new Category();
  $category_form = $("<%= j render 'category_form', category: @category %>");
  category.refresh_form($category_form);
});

app/views/categories/refresh_list.js.erb
$(document).ready(function(){
  var category = new Category();
  $categories_list = $("<%= j render 'categories/categories_list', categories: @categories %>");
  category.refresh_list($categories_list);
});