config/routes.rb
Socialfeed::Application.routes.draw do
  require 'sidetiq/web'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: { registrations: "users/registrations" }

  resources :feeds
  resources :entries
  resources :categories
  resources :filters
  resources :notifications
  resources :followings, only: [:index, :create, :destroy]

  devise_scope :user do
    authenticated :user do
      root to: 'entries#index', as: :authenticated_root
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/filter.rb
class Filter < ActiveRecord::Base
  acts_as_tenant :user
  #
  # schema
  #
  fields do
    keywords  :string
    list_type :boolean, default: false # true => whitelist, false => blacklist
    active    :boolean, default: true
    user_id   :integer
    timestamps
  end
  
  attr_accessible :keywords, :list_type, :active, :feed_id

  #
  # Validations
  # 
  validates :user_id, presence: true
  validates :keywords, presence: true

  #
  # Relations
  # 
  belongs_to :feed
  #
  # Methods
  # 

end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController

  def index
    @feeds = Feed.all
    if params[:id]
      @feed = Feed.find params[:id]
      if @feed.filter
        @filter = @feed.filter
      else
        @filter = Filter.new feed_id: @feed.id
      end
    end
    respond_to do |format|
      format.html
      format.js { render 'refresh_form', status: :ok }
    end
  end

  def destroy
    @filter = FiltersService.destroy params
    respond_to do |format|
      if @filter.errors.empty?
        @feeds = Feed.all
        @filter = nil
        format.js { render 'refresh_all', status: :ok }
      else
        format.js { render 'refresh_form', status: :unprocessable_entity }
      end
    end
  end

  def update
    @filter = FiltersService.update params
    respond_to do |format|
      if @filter.errors.empty?
        format.js
      else
        format.js{ render 'refresh_form', status: :unprocessable_entity }
      end
    end
  end

  def create
    @filter = FiltersService.create params
    respond_to do |format|
      if @filter.errors.empty?
        format.js
      else
        format.js{ render 'refresh_form', status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/filters/_feed_selection.html.haml
.row
  = form_tag filters_path, method: :get, remote: true do |f|
    .col-xs-12
      = select_tag :id, options_from_collection_for_select(feeds, :id, :name, feed._?.id), include_blank: true, class: 'form-control', data: {placeholder: t('placeholders.select_feed')} 

app/views/filters/_filter_form.html.haml
- if filter
  .box
    = simple_form_for filter, remote: true do |f|
      .row
        .col-xs-12
          .pull-right
            = f.input :list_type, as: :radio_buttons, collection: [[t('.whitelist'), true], [t('.blacklist'), false]], required: false, label: false, input_html: {class: 'radio'}, wrapper_html: {class: 'filter-type'}
          .clearfix
          = f.input :keywords, required: false, wrapper_html: {class: 'form-group keywords'}, input_html: {class: 'form-control', rows: 3, data: {role:'tagsinput'}}
          .clearfix
          = f.input :active, as: :boolean, input_html: {class: 'checkbox'}, wrapper_html: {class: 'filter-active'}
          = f.input :feed_id, as: :hidden
          .clearfix
      .row.top-margin
        .col-xs-2.col-xs-offset-8
          - if filter.persisted?
            = link_to filter_path(filter), method: :delete, remote: true, class: 'btn' do
              = t('.delete')
        .col-xs-2
          %button.btn.js-submit
            = t('.apply')

app/views/filters/create.js.erb
$(document).ready(function(){
  var app = new App();
  $filter_form = $("<%= j render 'filter_form', filter: @filter %>");
  app.refresh_content($('.js-form-container'), $filter_form, function(){
    app.apply_tagsinput();
  });
  alert('filter created successfully');
});

app/views/filters/index.html.haml
.secondary-view
  .panel
    .row
      .col-xs-8.col-xs-offset-2
        %h2
          = t('.filters')
        %p
          = t('.filter_out_certain_entries')
        .box
          .js-selection-form
            = render 'feed_selection', feeds: @feeds, feed: @feed
        .js-form-container
          = render 'filter_form', filter: @filter

= content_for :bottom_js do
  = javascript_include_tag "filters/filters"

app/views/filters/refresh_all.js.erb
$(document).ready(function(){
  var app = new App();
  $filter_form = $("<%= j render 'filter_form', filter: @filter %>");
  app.refresh_content($('.js-filter-form'), $filter_form, function(){
    $feed_selection = $("<%= j render 'feed_selection', feeds: @feeds, feed: @feed %>");
    app.refresh_content($('.js-selection-form'), $feed_selection, function(){
      app.apply_select2();
    });
  });
});

app/views/filters/refresh_form.js.erb
$(document).ready(function(){
  var app = new App();
  $filter_form = $("<%= j render 'filter_form', filter: @filter %>");
  app.refresh_content($('.js-form-container'), $filter_form, function(){
    app.apply_tagsinput();
  });
});

app/views/filters/update.js.erb
$(document).ready(function(){
  var app = new App();
  $filter_form = $("<%= j render 'filter_form', filter: @filter %>");
  app.refresh_content($('.js-form-container'), $filter_form, function(){
    app.apply_tagsinput();
  });
  alert('filter updated successfully');
});